//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yatsenko.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Tickets = new HashSet<Ticket>();
            this.Transports = new HashSet<Transport>();
        }
    
        public int IdRoute { get; set; }
        public string firstStop { get; set; }
        public string lastStop { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> dateLimit { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Transport> Transports { get; set; }
    }
}
