//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yatsenko.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int IdTicket { get; set; }
        public string condition { get; set; }
        public int idRoute { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
